spring:
  profiles:
    active: @profile.active@
  datasource:
    url: jdbc:mysql://localhost:3306/takeout?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  rabbitmq:
    virtual-host: /
    username: guest
    password: guest

server:
  port: 9002
