spring:
  profiles:
    active: @profile.active@
  datasource:
    url: jdbc:mysql://localhost:3306/takeout?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  rabbitmq:
    virtual-host: /
    username: guest
    password: guest
    publisher-confirm-type: CORRELATED # 确认模式 消息发送到exchange？
    publisher-returns: true # exchange 分发消息到队列？


server:
  port: 9002
