spring:
  profiles:
    active: @profile.active@
  datasource:
    url: jdbc:mysql://localhost:3306/takeout?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  rabbitmq:
    virtual-host: /
    username: guest
    password: guest
    publisher-confirm-type: CORRELATED # 异步确认消息
    publisher-returns: true # exchange -> 队列确认
    template:
      mandatory: true # 路由失败策略


server:
  port: 9002
