spring:
  profiles:
    active: @profile.active@
  datasource:
    url: jdbc:mysql://localhost:3306/takeout?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  rabbitmq:
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: AUTO # 消息处理状态
        prefetch: 1 #每次只能消费一条消息，处理完成才能获取下一个消息
        retry:
          enabled: true
          max-attempts: 5 # 最大重试次数

server:
  port: 9003
